# Generated by Django 5.1.6 on 2025-03-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('celular', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=8)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('grado', models.CharField(max_length=1)),
                ('seccion', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('celular', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('celular', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('apellido', models.CharField(max_length=100, unique=True)),
                ('grado', models.CharField(max_length=1)),
                ('seccion', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='alumnos.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(choices=[('embarazo', 'Embarazo'), ('madre_lactante', 'Madre Lactante'), ('tratamiento_psiquiatrico', 'Tratamiento Psiquiátrico'), ('certificado_medico', 'Certificado Médico'), ('sustancias_psicoactivas', 'Sustancias Psicoactivas'), ('evade_clases', 'Evade Clases'), ('alcohol', 'Consume Alcohol'), ('violencia', 'Violencia'), ('siseve', 'SISEVE'), ('tocamientos_indebidos', 'Tocamientos Indebidos')], max_length=255)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('accion_respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.accionrespuesta')),
                ('apoderado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.apoderado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.estudiante')),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.madre')),
                ('observacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.observacion')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.padre')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.tutor')),
            ],
        ),
    ]
