# Generated by Django 5.1.6 on 2025-03-17 20:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialalumno',
            name='reportes',
            field=models.ManyToManyField(blank=True, to='alumnos.reportealumno'),
        ),
        migrations.AlterField(
            model_name='historialalumno',
            name='estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='alumnos.estudiante'),
        ),
        migrations.AlterField(
            model_name='reportealumno',
            name='fecha_reporte',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reportealumno',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='alumnos.tutor'),
        ),
    ]
