# Generated by Django 5.1.6 on 2025-03-18 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_historialalumno_reportes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutores'},
        ),
        migrations.AddField(
            model_name='apoderado',
            name='estudiantes',
            field=models.ManyToManyField(related_name='apoderados', to='alumnos.estudiante'),
        ),
        migrations.AddField(
            model_name='madre',
            name='estudiantes',
            field=models.ManyToManyField(related_name='madres', to='alumnos.estudiante'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='alumnos.estudiante'),
        ),
        migrations.AddField(
            model_name='padre',
            name='estudiantes',
            field=models.ManyToManyField(related_name='padres', to='alumnos.estudiante'),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='madre',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='madre',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='padre',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='padre',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportealumno',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.tutor'),
        ),
    ]
